### ISSUE TITLE
Consider Using Template Strings

### ISSUE THREAD

**Issue by Ellisande** [krames12/pug-check#7]
Its more of a preference thing but using template string can make it easier to visualize when you have several variables being concatenated into a single string.

Example:
https://github.com/krames12/pug-check/blob/master/server.js#L18

```js
    blizzRequestUrl = 'https://' + req.params.region + '.api.battle.net/wow/character/' + req.params.server +  '/' + cleanCharacterName + '?fields=progression,items&locale=en_US&apikey=' + process.env.BLIZZ_KEY,
```

You could use a template string by using backticks instead of quotes and `${variable}` for where the variables should go.

```js
  const region = req.params.region;
  const server = req.params.server;
  const apiKey = process.env.BLIZZ_KEY;
  const blizzRequestUrl = `https://${region}.api.battle.net/wow/character/${server}/${cleanCharacterName}?fields=progression,items&locale=en_US&apikey=${apiKey}`
```

**Comment by krames12** [comment]
I had no idea about template literals. Appreciate the info and I'm going to get a PR on this asap.
